<a href="https://colab.research.google.com/github/fordinand45/BDP_A_Kelompok_3/blob/main/GROUPDTSA3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Mempersiapkan *environment* untuk melakukan analisa data

In [3]:
import os
os.environ['KAGGLE_CONFIG_DIR'] = '/content'

In [5]:
!kaggle datasets download -d anshtanwar/global-data-on-sustainable-energy

Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /content/kaggle.json'
401 - Unauthorized

In [6]:
import pandas as pd

In [7]:
import plotly.express as px

cara mengubah *dataset* format **zip** ke format **csv** : !unzip \*.zip && rm * .zip

In [11]:
df = pd.read_csv('global-data-sustainable-energy .csv')
df

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
0,Afghanistan,2000,1.613591,6.2,9.22,20000.0,44.99,0.16,0.0,0.31,...,302.59482,1.64,760.000000,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
1,Afghanistan,2001,4.074574,7.2,8.86,130000.0,45.60,0.09,0.0,0.50,...,236.89185,1.74,730.000000,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
2,Afghanistan,2002,9.409158,8.2,8.47,3950000.0,37.83,0.13,0.0,0.56,...,210.86215,1.40,1029.999971,NaN,NaN,179.426579,60,652230.0,33.939110,67.709953
3,Afghanistan,2003,14.738506,9.5,8.09,25970000.0,36.66,0.31,0.0,0.63,...,229.96822,1.40,1220.000029,NaN,8.832278,190.683814,60,652230.0,33.939110,67.709953
4,Afghanistan,2004,20.064968,10.9,7.75,NaN,44.24,0.33,0.0,0.56,...,204.23125,1.20,1029.999971,NaN,1.414118,211.382074,60,652230.0,33.939110,67.709953
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644,Zimbabwe,2016,42.561730,29.8,62.88,30000.0,81.90,3.50,0.0,3.32,...,3227.68020,10.00,11020.000460,NaN,0.755869,1464.588957,38,390757.0,-19.015438,29.154857
3645,Zimbabwe,2017,44.178635,29.8,62.33,5570000.0,82.46,3.05,0.0,4.30,...,3068.01150,9.51,10340.000150,NaN,4.709492,1235.189032,38,390757.0,-19.015438,29.154857
3646,Zimbabwe,2018,45.572647,29.9,82.53,10000.0,80.23,3.73,0.0,5.46,...,3441.98580,9.83,12380.000110,NaN,4.824211,1254.642265,38,390757.0,-19.015438,29.154857
3647,Zimbabwe,2019,46.781475,30.1,81.40,250000.0,81.50,3.66,0.0,4.58,...,3003.65530,10.47,11760.000230,NaN,-6.144236,1316.740657,38,390757.0,-19.015438,29.154857
3648,Zimbabwe,2020,52.747670,30.4,80.61,30000.0,81.90,3.40,0.0,4.19,...,2680.13180,10.00,NaN,NaN,-6.248748,1214.509820,38,390757.0,-19.015438,29.154857

informasi dataset muncul

In [12]:
df.shape

(3649, 21)

In [13]:
df.head(200)

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
0,Afghanistan,2000,1.613591,6.2,9.22,20000.0,44.99,0.16,0.0,0.31,...,302.59482,1.64,760.000000,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
1,Afghanistan,2001,4.074574,7.2,8.86,130000.0,45.60,0.09,0.0,0.50,...,236.89185,1.74,730.000000,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
2,Afghanistan,2002,9.409158,8.2,8.47,3950000.0,37.83,0.13,0.0,0.56,...,210.86215,1.40,1029.999971,NaN,NaN,179.426579,60,652230.0,33.939110,67.709953
3,Afghanistan,2003,14.738506,9.5,8.09,25970000.0,36.66,0.31,0.0,0.63,...,229.96822,1.40,1220.000029,NaN,8.832278,190.683814,60,652230.0,33.939110,67.709953
4,Afghanistan,2004,20.064968,10.9,7.75,NaN,44.24,0.33,0.0,0.56,...,204.23125,1.20,1029.999971,NaN,1.414118,211.382074,60,652230.0,33.939110,67.709953
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,Austria,2006,100.000000,100.0,NaN,NaN,26.64,21.62,0.0,40.66,...,50921.68400,3.38,74099.998470,28.591210,3.454042,40635.281820,109,83871.0,47.516231,14.550072
196,Austria,2007,100.000000,100.0,NaN,NaN,28.99,19.74,0.0,43.17,...,49669.19500,3.20,71239.997860,30.980610,3.727415,46855.771750,109,83871.0,47.516231,14.550072
197,Austria,2008,100.000000,100.0,NaN,NaN,29.68,19.97,0.0,44.53,...,50475.00800,3.18,70730.003360,31.345478,1.460424,51708.765750,109,83871.0,47.516231,14.550072
198,Austria,2009,100.000000,100.0,NaN,NaN,31.31,19.12,0.0,47.18,...,48765.18400,3.14,64419.998170,34.322514,-3.764578,47963.179400,109,83871.0,47.516231,14.550072
199,Austria,2010,100.000000,100.0,NaN,NaN,31.15,22.92,0.0,44.99,...,50240.96000,3.29,69959.999080,31.605642,1.837094,46858.043270,109,83871.0,47.516231,14.550072

# Exploring the Connection: Does **CO2** Emission Correlate with a Nation's **Land** **Area**?

In [14]:
land_data = df[['Entity', 'Land Area(Km2)']]
land_data.head(100)

                 Entity  Land Area(Km2)
0           Afghanistan        652230.0
1           Afghanistan        652230.0
2           Afghanistan        652230.0
3           Afghanistan        652230.0
4           Afghanistan        652230.0
..                  ...             ...
95  Antigua and Barbuda           443.0
96  Antigua and Barbuda           443.0
97  Antigua and Barbuda           443.0
98  Antigua and Barbuda           443.0
99  Antigua and Barbuda           443.0

[100 rows x 2 columns]

In [15]:
land_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3649 entries, 0 to 3648
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Entity          3649 non-null   object
 1   Land Area(Km2)  3648 non-null   float64
dtypes: float64(1), object(1)
memory usage: 57.1+ KB

 Mengecek apakah ada value yang bernilai ***null*** pada data kita.

In [16]:
land_data.isnull().sum()

Entity            0
Land Area(Km2)    1
dtype: int64

In [17]:
land_data_dropped = land_data.dropna(axis=0)

In [18]:
land_data_dropped.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3648 entries, 0 to 3648
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Entity          3648 non-null   object
 1   Land Area(Km2)  3648 non-null   float64
dtypes: float64(1), object(1)
memory usage: 85.5+ KB

In [19]:
land_data_dropped.isnull().sum()

Entity            0
Land Area(Km2)    0
dtype: int64

In [20]:
land_data_dropped.shape

(3648, 2)

Mengambil informasi tentang region ( nation) dalam DataFrame

In [21]:
regions = land_data_dropped['Entity'].unique()
regions

array(['Afghanistan', 'Albania', 'Algeria', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba',
       'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain',
       'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin',
       'Bermuda', 'Bhutan', 'Bosnia and Herzegovina', 'Botswana',
       'Brazil', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia',
       'Cameroon', 'Canada', 'Cayman Islands', 'Central African Republic',
       'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo',
       'Costa Rica', 'Croatia', 'Cuba', 'Cyprus', 'Czechia', 'Denmark',
       'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon',
       'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada',
       'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti',
       'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iraq',
       'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan',
       'Kazakhstan', 'Kenya', 'Kiribati', 'Kuwait', 'Kyrgyzstan',
       'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Lithuania',
       'Luxembourg', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives',
       'Mali', 'Malta', 'Mauritania', 'Mauritius', 'Mexico', 'Mongolia',
       'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia',
       'Nauru', 'Nepal', 'Netherlands', 'New Caledonia', 'New Zealand',
       'Nicaragua', 'Niger', 'Nigeria', 'North Macedonia', 'Norway',
       'Oman', 'Pakistan', 'Panama', 'Papua New Guinea', 'Paraguay',
       'Peru', 'Philippines', 'Poland', 'Portugal', 'Puerto Rico',
       'Qatar', 'Romania', 'Rwanda', 'Saint Kitts and Nevis',
       'Saint Lucia', 'Saint Vincent and the Grenadines', 'Samoa',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South Sudan',
       'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden', 'Switzerland',
       'Tajikistan', 'Thailand', 'Togo', 'Tonga', 'Trinidad and Tobago',
       'Tunisia', 'Turkey', 'Turkmenistan', 'Tuvalu', 'Uganda', 'Ukraine',
       'United Arab Emirates', 'United Kingdom', 'United States',
       'Uruguay', 'Uzbekistan', 'Vanuatu', 'Yemen', 'Zambia', 'Zimbabwe'],
      dtype=object)

Mengubah Tipe data dari Land Area Yaitu *Object*

In [22]:
# Gets every value of Land Area
land = land_data_dropped['Land Area(Km2)'].unique()

# New list for land area as int type
land_int = []

# Iterates through every value in land, convert it to a string and handle decimals
for num in land:
    num_str = str(num)  # Convert the value to a string
    if '.' in num_str:  # Check if the string contains a decimal point
        int_part, _ = num_str.split('.')  # Split at the decimal point and take the integer part
        land_int.append(int(int_part))  # Convert and append the integer value
    else:
        land_int.append(int(num_str))  # If there's no decimal, directly convert and append

# Now land_int contains the land areas as integers without commas or decimals

Menaruh kembali ***region*** dan ***land*** are kita kedalam DataFrame

In [35]:
land_data_dropped_df = pd.DataFrame([regions, pd.to_numeric(land_int)], index=['Regions', 'Land'])


land_data_dropped_df = land_data_dropped_df.T

land_data_dropped_df.head()

               Regions     Land
0          Afghanistan   652230
1              Albania    28748
2              Algeria  2381741
3               Angola  1246700
4  Antigua and Barbuda      443

In [24]:
land_data_dropped_df = pd.DataFrame([regions, pd.to_numeric(land_int)], index=['Regions', 'Land'])


land_data_dropped_df = land_data_dropped_df.T

sorted_land_data = land_data_dropped_df.sort_values(by='Land', ascending=False)


top_10_regions = sorted_land_data.head(10)
print(top_10_regions)

           Regions     Land
29          Canada  9984670
168  United States  9833517
34           China  9596960
23          Brazil  8515770
8        Australia  7741220
73           India  3287263
5        Argentina  2780400
82      Kazakhstan  2724900
2          Algeria  2381741
37           Congo  2345409

In [25]:
land_data_dropped_df.shape
land_data_dropped_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175 entries, 0 to 174
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Regions  175 non-null    object
 1   Land     175 non-null    object
dtypes: object(2)
memory usage: 2.9+ KB

In [26]:
# Creates a graph called graph
graph = px.bar(land_data_dropped_df, x='Regions', y='Land', labels={'Land': 'Land Area - km2', 'Entity': 'Regions'})

# Updates graph layout/styles
graph.update_layout(title={
    'text': 'Countries Land Area - in km2',
    'x': 0.5,
})

graph.show()

Kita akan mencari seberapa besar emisi yang dihasilan dari 5 negara terbesar

In [27]:
emissions_co2_data = df[['Entity', 'Year', 'Value_co2_emissions_kt_by_country']].rename(columns={'Value_co2_emissions_kt_by_country': 'co2'})

emissions_co2_data.isnull().sum()

Entity      0
Year        0
co2       428
dtype: int64

In [28]:
emissions_co2_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3649 entries, 0 to 3648
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Entity  3649 non-null   object
 1   Year    3649 non-null   int64
 2   co2     3221 non-null   float64
dtypes: float64(1), int64(1), object(1)
memory usage: 85.6+ KB

values yang hilang akan kita drop

In [29]:
emissions_co2_data = emissions_co2_data.dropna(axis=0)

Memisahkan tiap region(countries) dalam dataframe yang berbeda untuk melakukan plot pada setiap graph

In [30]:
# Canada
canada_emissions_co2_data= emissions_co2_data[(emissions_co2_data['Entity'] == 'Canada')].dropna()

# United States
united_states_emissions_co2_data = emissions_co2_data[(emissions_co2_data['Entity'] == 'United States')].dropna()

# China
china_emissions_co2_data = emissions_co2_data[(emissions_co2_data['Entity'] == 'China')].dropna()

# Brazil
brazil_emissions_co2_data = emissions_co2_data[(emissions_co2_data['Entity'] == 'Brazil')].dropna()

# Australia
autralia_emissions_co2_data = emissions_co2_data[(emissions_co2_data['Entity'] == 'Australia')].dropna()

Melakukan plotting kepada 5 *negara* terbesar berdasarkan besaran(values) emisi

In [31]:
# Imports important packages from plotly
from plotly.subplots import make_subplots
import plotly.graph_objects as go

# Create individual subplots
subplot_canada = go.Figure()
subplot_canada.add_trace(go.Bar(x=canada_emissions_co2_data['Year'], y=canada_emissions_co2_data['co2']))
subplot_canada.update_layout(title_text='Canada')

subplot_us = go.Figure()
subplot_us.add_trace(go.Bar(x=united_states_emissions_co2_data['Year'], y=united_states_emissions_co2_data['co2']))
subplot_us.update_layout(title_text='United States')

subplot_china = go.Figure()
subplot_china.add_trace(go.Bar(x=china_emissions_co2_data['Year'], y=china_emissions_co2_data['co2']))
subplot_china.update_layout(title_text='China')

subplot_brazil = go.Figure()
subplot_brazil.add_trace(go.Bar(x=brazil_emissions_co2_data['Year'], y=brazil_emissions_co2_data['co2']))
subplot_brazil.update_layout(title_text='Brazil')

subplot_australia = go.Figure()
subplot_australia.add_trace(go.Bar(x=autralia_emissions_co2_data['Year'], y=autralia_emissions_co2_data['co2']))
subplot_australia.update_layout(title_text='Australia')

# Arrange the subplots using make_subplots
graph = make_subplots(
    rows=2, cols=3,
    subplot_titles=('Canada', 'United States', 'China', 'Brazil', 'Australia')
)

graph.add_trace(subplot_canada.data[0], row=1, col=1)
graph.add_trace(subplot_us.data[0], row=1, col=2)
graph.add_trace(subplot_china.data[0], row=1, col=3)
graph.add_trace(subplot_brazil.data[0], row=2, col=1)
graph.add_trace(subplot_australia.data[0], row=2, col=2)

# Updates subplot layout
graph.update_layout(height=800, width=1000, showlegend=False, title={
    'text': 'CO2 emission - in kiloton - by the five biggest countries in the world, per year',
    'x': 0.5
})

# Shows subplot
graph.show()

# Emisi CO2 dan Dukungan Keuangan Internasional untuk Energi Bersih

In [32]:
financial = df[['Entity', 'Year', 'Financial flows to developing countries (US $)']]

financial_flowdata_2017 = financial[(financial['Year'] == 2017)].dropna()

In [33]:
fig_financial_data_2017 = px.bar(financial_flowdata_2017, x='Entity', y='Financial flows to developing countries (US $)')

fig_financial_data_2017.update_layout(title={
    'text': 'International finance received for clean energy in USD per country',
    'x': 0.5
})

fig_financial_data_2017.show()